[OPTION]
TRIG_SET_DELAY_INSPECTION=0
TRIG_SET_TIME_INSPECTION=10
TRIG_SET_DELAY_BARCODE=0
TRIG_SET_TIME_BARCODE=10

[COUNT]
COUNT_00=844
COUNT_01=0

[MESSAGE]
001=Prohibition
002=Prohibit facility operation !!!
003=The equipment is undergoing inspection. Do not operate the equipment. !!!

;001=작업 금지
;002=설비 작업 금지 !!!
;003=설비 점검중 입니다. 작업 진행 하지 마세요. !!!
